### ISSUE TITLE
Feature Request: Support for css styles without selectors

### ISSUE THREAD

**Issue by brandonmcconnell** [pushqrdx/vscode-inline-html#37]
Currently, this is supported:

```scss
/*css*/`
  .selector {
    display: block;
  }
`
```

But this is not:

```
/*css*/`
  display: block;
`
```

I propose adding a new syntax specific for CSS styles—a commonly used pattern when adding styles to an element inline in JavaScript frameworks—like this:

```c#
/*style*/`
  display: block;
`
```
