### ISSUE TITLE
Support for CSS tag

### ISSUE THREAD

**Issue by drachehavoc** [pushqrdx/vscode-inline-html#7]
Please add the possibility to intellisense for CSS, something like this:

```css
css`
    div {
        color: red
    }
`
```
